---
title: "Landings"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---
    
# SET-UP
```{r markdwon, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 140)
```    

## settings
```{r settings, message = F}
source('0.0_settings.R')
```

## load all data
```{r data, message = F}
load(paste0(dir.rdat, "catch.Rdata"))
gear.groups <- read.csv(paste0(dir.dat,'gear_groupings.csv'))
catch <- merge(catch, gear.groups,  all.x = T)
```

# TABLES {.tabset}

## Total
```{r tabel total}
df.tot <- catch
df.tot[df.tot$country!='Canada','country'] <- 'Foreign'
df.tot <- ddply(df.tot,c('year','country'),summarise,catch=sum(catch,na.rm=T))
df.tot <- reshape2::dcast(df.tot,year~country,value.var = 'catch')
df.tot[is.na(df.tot)] <- 0
df.tot$total <- with(df.tot,Canada+Foreign)

kable(df.tot,digits=0,row.names = FALSE, caption='Annual landings (t) within Canada’s Exclusive Economic Zone')

```

## Province
```{r tabel province}
df.prov <- catch[catch$source=='ziff',]                                            # how did Thomas got provincial from 1985 onwards?
df.prov <- ddply(df.prov,c('year','prov'),summarise,catch=sum(catch,na.rm=T))
df.prov <- reshape2::dcast(df.prov,year~prov,value.var = 'catch')
df.prov$unknown <- NULL                                                            

kable(df.prov,digits=0,row.names = FALSE, caption='Annual landings (t) by province')

```

## NAFO
```{r table nafo}
df.nafo <- catch
df.nafo <- ddply(df.nafo,c('year','nafo'),summarise,catch=sum(catch,na.rm=T))
df.nafo <- reshape2::dcast(df.nafo,year~nafo,value.var = 'catch',fill = 0)
df.nafo$'NA' <- NULL                                                            

kable(df.nafo,digits=0,row.names = FALSE, caption='Annual landings (t) by NAFO division')

```

## Gear
```{r table gear}
df.gear <- catch
df.gear <- ddply(df.gear,c('year','gear'),summarise,catch=sum(catch,na.rm=T))
df.gear <- reshape2::dcast(df.gear,year~gear,value.var = 'catch',fill = 0)
df.gear$'NA' <- NULL                                                            

kable(df.gear,digits=0,row.names = FALSE, caption='Annual landings (t) by gear type')

```

## Gear x NAFO
```{r table gear.nafo}
y <- 2018:2020                                                               #(3 last years with complete date)
df.gearnafo <- catch[catch$year %in% y,]
df.gearnafo <- ddply(df.gearnafo,c('gear','nafo'),summarise,catch=sum(catch,na.rm=T))
df.gearnafo <- reshape2::dcast(df.gearnafo,nafo~gear,value.var = 'catch',fill = 0)
df.gearnafo$'NA' <- NULL                                                            

kable(df.gearnafo,digits=0,row.names = FALSE, caption='Annual landings (t) by gear type and NAFO division')

```

## Top fisheries
```{r table top}
y <- 2018:2020                                                               # years to consider (one or multiple)
df.top <- catch[catch$year %in% y,]
df.top <- ddply(df.top,c('year','gear','nafo'),summarise,catch=sum(catch,na.rm=T))
df.top <- ddply(df.top,c('year'),transform,catch.perc=catch*100/sum(catch,na.rm=T))
df.top <- ddply(df.top,c('gear','nafo'),summarise,catch.perc=mean(catch.perc,na.rm=T),catch.mean=mean(catch),catch.tot=sum(catch)) # average percentage
df.top <- df.top[order(df.top$catch.perc,decreasing = TRUE),]
df.top$catch.perc <- round(df.top$catch.perc,0)

kable(df.top[df.top$catch.perc>0,],digits=0,row.names = FALSE, caption='Top fisheries 2018-2020')

```