---
title: "Landings: FAQ"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---

# SET-UP
```{r markdown, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6)
options(width = 200)
```    

## settings
```{r settings, message = F}
source('0.0_settings.R')
```

## load all data
```{r data, message = F}
load(paste0(dir.rdat, "ziff.Rdata"))
```

# How much do gillnets and handlines/jiggers usually land?
Helpful to determine catch allowed to keep for sample collection.
```{r q1, message = F}
year <- 2011:2021

# subset for years
sub <- ziff[ziff$year %in% year,]

# subset for gears
sub$gear.cat2 <- substr(sub$gear.cat,1,2)
sub <- sub[sub$gear.cat2 %in% c('GN','LH'),]
```

## TABLES AND PLOTS {.tabset}

### Table
```{r table percentile}
sub$c <- round(sub$catch,0)

df <- data.frame(catch=seq(0,1000,100))
df$perc <- round(ecdf(sub$c)(df$catch)*100,0)

kable(df,digits=0,row.names = FALSE, caption='Percentage of landings equal to or lower than indicated')

```

### boxplot overall
```{r plot boxgen}
ggplot(sub,aes(x=gear.cat2,y=catch,fill=as.factor(year)))+
    geom_boxplot()+
    scale_y_log10()+
    labs(y='Landings per trip (kg)',x='Gear categorie',fill='Year')
```

### boxplot by region
```{r plot boxreg}
ggplot(sub[sub$prov.land!='NL',],aes(x=gear.cat2,y=catch,fill=as.factor(year)))+
    geom_boxplot()+
    scale_y_log10()+
    labs(y='Landings per trip (kg)',x='Gear categorie',fill='Year')+
    facet_wrap(~prov.land)

```

### ecdf
```{r ecdf}
plot(ecdf(sub$c),xlim=c(0,5000),xlab="Landings per trip (kg)")
```